Repository Please-Hug/Please-Hug_FrontEnd, pull requests merged in 2025-07, with the labels that each got.

#65 칭찬 글 없을 시 디폴트 값 조회, 칭찬 등록 시 바로 새로고침 등록
  src/api/praiseService.js
  src/components/Praise/PraiseCard.jsx
  src/components/Praise/PraiseModal.jsx
  src/pages/praise/PraisePage.jsx
  src/pages/praise/PraisePage.module.css
Labels: 리팩토링

#69 Update 달력 커스텀
  src/components/Praise/DateRangePickerCustom.css
  src/components/Praise/DateRangePickerModal.jsx
  src/components/Praise/DateRangePickerModal.module.css
Labels: 리팩토링

#74 Feature/#73 상점 스타일 수정 및 수정, 삭제 기능 연동
  src/api/axiosInstance.js
  src/api/shopService.js
  src/api/studyDiaryService.js
  src/components/Shop/GiftModal.jsx
  src/components/Shop/ProductCard.jsx
  src/components/Shop/ProductCard.module.scss
  src/components/Shop/ProductEditForm.jsx
  src/components/Shop/ProductEditForm.module.scss
  src/components/common/Modal/Modal.jsx
  src/components/common/Modal/Modal.module.scss
  src/components/common/Sidebar/Sidebar.jsx
  src/components/common/Sidebar/SidebarUserMenu.jsx
  src/layouts/MainLayout.jsx
  src/pages/Shop/AdminShopPage.jsx
  src/pages/Shop/ShopHistoryPage.jsx
  src/pages/Shop/ShopHistoryPage.module.scss
  src/pages/Shop/ShopPage.jsx
  src/pages/Shop/ShopPage.module.scss
  src/pages/user/MyInfoPage.jsx
  src/stores/tokenPayloadStore.js
Labels: 기능 개발, 버그, 성능 개선, 리팩토링

#75 북마크 ui 구현
  src/api/bookmark.js
  src/components/Dashboard/BookmarkForm.jsx
  src/components/Dashboard/BookmarkList.jsx
  src/components/Dashboard/BookmarkSection.jsx
  src/pages/user/DashboardPage.jsx
  src/pages/user/DashboardPage.module.scss
Labels: 기능 개발

#84 Feature/#82 미션 어드민 기능 추가
  src/api/missionService.js
  src/components/Mission/AddMissionGroupModal.jsx
  src/components/Mission/AddMissionModal.jsx
  src/components/Mission/EditMissionGroupModal.jsx
  src/components/Mission/EditMissionModal.jsx
  src/components/Mission/MissionItem.jsx
  src/components/Mission/MissionItem.module.scss
  src/components/common/Modal/Modal.module.scss
  src/components/common/TabComponent/TabComponent.jsx
  src/components/common/TabComponent/TabComponent.module.scss
  src/layouts/MainLayout.jsx
  src/pages/Shop/AdminShopPage.jsx
  src/pages/mission/MissionOverviewPage.jsx
  src/pages/mission/MissionOverviewPage.module.scss
Labels: 기능 개발

#90 Feature/#89 미션 힌트 기능 추가
  src/components/Mission/AddMissionModal.jsx
  src/components/Mission/EditMissionModal.jsx
  src/components/Mission/MissionDetailCard.jsx
  src/components/Mission/MissionDetailCard.module.scss
  src/components/common/Modal/Modal.module.scss
Labels: 기능 개발

#99 feat: 강사 미션 피드백 페이지 구현
  src/api/missionService.js
  src/components/Mission/ChallengeDetailModal.jsx
  src/components/Mission/ChallengeDetailModal.module.scss
  src/components/common/Sidebar/Sidebar.jsx
  src/pages/mission/ChallengeListPage.jsx
  src/pages/mission/ChallengeListPage.module.scss
  src/routes/user.routes.jsx
Labels: 기능 개발

#100 알림 배움일기 알림 기능
  package-lock.json
  package.json
  src/api/notificationService.js
  src/components/common/SideModal/Notification.jsx
  src/components/common/Sidebar/Sidebar.jsx
Labels: 기능 개발

#104 Feature/#101 유저 랭킹에 참여중인 미션 그룹 표시
  src/pages/user/RankingPage.jsx
Labels: 버그

#105 관리자 도메인: 회원관리 페이지 구현 (css는 아직 미구현)
  src/api/adminService.js
  src/components/Admin/UserTable.jsx
  src/layouts/AdminLayout.jsx
  src/pages/admin/AdminUserDetail.jsx
  src/pages/admin/AdminUsersList.jsx
  src/pages/user/DashboardPage.jsx
  src/routes/admin.routes.jsx
Labels: 기능 개발

#110 대시보드 메뉴 및 사이드바에서 없는 기능 주석처리 및 README.md 수정
  README.md
  src/components/Dashboard/DashboardMenu.jsx
  src/components/common/Sidebar/Sidebar.jsx
Labels: 리팩토링

#118 관리자 회원전체검색 페이징 개선
  src/api/adminService.js
  src/components/Admin/UserTable.jsx
  src/components/Admin/UserTable.module.scss
  src/pages/admin/AdminUsersList.jsx
  src/pages/admin/AdminUsersList.module.scss
Labels: 버그
