Repository Please-Hug/Please-Hug_FrontEnd, pull requests merged in 2025-06, with the labels that each got.

#2 Feature/#1 대시보드 리팩토링
  src/components/Dashboard/AttendanceCheck.jsx
  src/components/Dashboard/AttendanceCheck.module.scss
  src/components/Dashboard/DailyQuest.jsx
  src/components/Dashboard/DailyQuest.module.scss
  src/components/Dashboard/DailyQuestItem.jsx
  src/components/Dashboard/DashboardMenu.jsx
  src/components/Dashboard/DashboardMenu.module.scss
  src/components/Dashboard/LearningPlanItem.jsx
  src/components/Dashboard/LearningPlanItem.module.scss
  src/components/Dashboard/LearningPlans.jsx
  src/components/Dashboard/LearningPlans.module.scss
  src/components/Dashboard/RecentDiary.jsx
  src/components/Dashboard/RecentDiary.module.scss
  src/components/Dashboard/RecentDiaryItem.jsx
  src/components/Dashboard/RecentLearning.jsx
  src/components/Dashboard/RecentLearning.module.scss
  src/components/Dashboard/UserProfile.jsx
  src/components/Dashboard/UserProfile.module.scss
  src/pages/user/DashboardPage.jsx
  src/pages/user/DashboardPage.module.scss
Labels: 리팩토링

#8 Feature/#7 미션 HTML + CSS
  src/components/Mission/MissionItem.jsx
  src/components/Mission/MissionItem.module.scss
  src/components/common/Sidebar/Sidebar.jsx
  src/hooks/dummy
  src/pages/mission/MissionOverviewPage.jsx
  src/pages/mission/MissionOverviewPage.module.scss
  src/routes/public.routes.jsx
  src/routes/user.routes.jsx
  src/services/dummy
  src/stores/dummy
  src/utils/dummy
Labels: 기능 개발

#11 feat: 퀘스트 페이지 및 아이템 컴포넌트 추가, 사이드바 메뉴 업데이트
  src/apis/dummy
  src/components/Quest/QuestItem.jsx
  src/components/Quest/QuestItem.module.scss
  src/components/common/Sidebar/Sidebar.jsx
  src/pages/Quest/QuestPage.jsx
  src/pages/Quest/QuestPage.module.scss
  src/routes/user.routes.jsx
Labels: 기능 개발

#16 feat: 사용자 프로필 및 로그아웃 기능 추가, 사이드바 사용자 메뉴 구현
  src/api/userService.js
  src/components/common/Sidebar/Sidebar.jsx
  src/components/common/Sidebar/Sidebar.module.scss
  src/components/common/Sidebar/SidebarUserMenu.jsx
  src/components/common/Sidebar/SidebarUserMenu.module.scss
  src/layouts/MainLayout.jsx
  src/pages/user/DashboardPage.jsx
  src/pages/user/LogoutPage.jsx
  src/routes/user.routes.jsx
  src/services/dummy
  src/stores/dummy
  src/stores/userStore.js
Labels: 기능 개발

#21 Feature/#20 미션 페이지 시인성 향상
  src/api/missionService.js
  src/components/Mission/MissionItem.jsx
  src/components/Mission/MissionItem.module.scss
  src/pages/mission/MissionOverviewPage.jsx
Labels: 기능 개발, 리팩토링

#24 Feature/#23 사이드 모달 구현
  src/components/Mission/MissionItem.jsx
  src/components/common/SideModal/SideModal.jsx
  src/pages/mission/MissionOverviewPage.jsx
  src/pages/mission/MissionOverviewPage.module.scss
Labels: 기능 개발

#33 미션 작업 관련 API 및 상태 관리 기능 추가
  src/api/missionService.js
  src/components/Mission/MissionDetailCard.jsx
  src/components/Mission/TaskItem.jsx
  src/components/Mission/TaskItem.module.scss
  src/utils/missionStateMap.js
  src/utils/missionTaskStateMap.js
Labels: 기능 개발, 리팩토링

#40 Commit 날짜 기준 칭찬 게시물 조회
  package-lock.json
  package.json
  src/api/praiseService.js
  src/api/userService.js
  src/components/Praise/DateRangePickerCustom.css
  src/components/Praise/DateRangePickerModal.jsx
  src/components/Praise/DateRangePickerModal.module.css
  src/components/Praise/PraiseCard.jsx
  src/components/Praise/PraiseCard.module.css
  src/pages/praise/PraisePage.jsx
Labels: 기능 개발

#41 Feature/#38 미션 상세 페이지 및 브레드크럼
  src/api/missionService.js
  src/components/Mission/MissionDetailCard.jsx
  src/components/Mission/MissionDetailCard.module.scss
  src/components/Mission/MissionFeedbackCard.jsx
  src/components/Mission/MissionFeedbackCard.module.scss
  src/components/Mission/MissionTask.jsx
  src/components/Mission/MissionTask.module.scss
  src/components/common/Breadcrumb/Breadcrumb.jsx
  src/pages/mission/MissionDetailPage.jsx
  src/pages/mission/MissionDetailPage.module.scss
  src/pages/mission/MissionGroupPage.jsx
  src/pages/mission/MissionOverviewPage.jsx
  src/pages/user/DashboardPage.jsx
  src/routes/user.routes.jsx
  src/stores/breadcrumbStore.js
Labels: 기능 개발, 리팩토링

#46 Commit 칭찬 상세조회
  package-lock.json
  src/api/praiseService.js
  src/components/Praise/PraiseCard.jsx
  src/components/Praise/PraiseDetailModal.jsx
  src/components/Praise/PraiseDetailModal.module.css
  src/pages/praise/PraisePage.jsx
Labels: 기능 개발

#48 Studydiary 초기 구현
  src/api/studyDiaryService.js
  src/components/common/Sidebar/Sidebar.jsx
  src/pages/auth/RegisterPage.jsx
  src/pages/studyDiary/MyStudyDiaryActivity.jsx
  src/pages/studyDiary/MyStudyDiaryActivity.module.scss
  src/pages/studyDiary/StudyDiaryEditPage.jsx
  src/pages/studyDiary/StudyDiaryEditPage.module.scss
  src/pages/studyDiary/StudyDiaryListPage.jsx
  src/pages/studyDiary/StudyDiaryListPage.module.scss
  src/pages/studyDiary/StudyDiaryViewPage.jsx
  src/pages/studyDiary/StudyDiaryViewPage.module.scss
  src/pages/studyDiary/StudyDiaryWritePage.jsx
  src/pages/studyDiary/StudyDiaryWritePage.module.scss
  src/routes/public.routes.jsx
  src/routes/user.routes.jsx
Labels: 기능 개발

#53 Commit 반응 좋은 칭찬글
  src/api/praiseService.js
  src/components/Praise/PopularPraiseList.jsx
  src/components/Praise/PopularPraiseList.module.css
  src/components/Praise/PraiseDetailModal.jsx
  src/components/Praise/PraiseDetailModal.module.css
  src/pages/praise/PraisePage.jsx
Labels: 기능 개발

#56 출석체크 api 연동
  src/api/attendanceService.js
  src/components/Dashboard/AttendanceCheck.jsx
  src/components/Dashboard/AttendanceCheck.module.scss
Labels: 기능 개발
